Basic template
rossyndicate/bookdown_template pull request #1
Opened 2023-04-03 20:53 UTC by mbrousil

Basic bookdown template including references. Sections named for parts of a paper.

2023-04-03 21:56 UTC, steeleb requested changes
Dig it!

Can you add a bit more high-level instruction for this repo - as is in: this fake book has 5 chapters (_list the chapters_) that are all pulled together in the `index.Rmd` file. 

Related: should `01-abstract.Rmd` be a thing?

2023-04-03 21:56 UTC, steeleb commented on index.Rmd
> +1. Find the **Build** pane in the RStudio IDE, and
Maybe add a screen shot?

2023-04-03 21:56 UTC, steeleb commented on index.Rmd
> +1. Find the **Build** pane in the RStudio IDE, and
Maybe add a screen shot?

2023-04-03 21:56 UTC, steeleb commented on index.Rmd
> +# url: your book url like https://bookdown.org/yihui/bookdown
suggestion:
# url: your book url like https://bookdown.org/USERNAME/REPO

2023-04-03 21:56 UTC, steeleb commented on _bookdown.yml
does this automatically populate? Maybe note in the readme the minimum things someone needs to edit in order to make a bookdown?

2023-04-03 21:56 UTC, steeleb commented on README.md
> +The **bookdown** book: https://bookdown.org/yihui/bookdown/
'We highly suggest you review chapter 1 of this book before forking this repo!'

2023-04-04 16:22 UTC, mbrousil commented on index.Rmd
> +1. Find the **Build** pane in the RStudio IDE, and
This was auto-populated. I've never used this myself so I deleted it and now just show the code option.

2023-04-04 16:38 UTC, steeleb commented
Suhweet. 

This looks great! Merging this sucker.

2023-04-04 16:38 UTC, merged